### ISSUE TITLE
1.8 java isn't supported

### ISSUE THREAD

**Issue by Boryte** [aternosorg/mclogs#77]
`[02:46:15] [ERROR]: Could not load 'plugins/mclogs-bukkit-2.6.3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidPluginException: java.lang.UnsupportedClassVersionError: gs/mclo/bukkit/MclogsPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:134) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.plugin.SimplePluginManager.loadPlugin(SimplePluginManager.java:314) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:246) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugins(SourceFile:335) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(SourceFile:324) ~[spigot.jar:git-iSpigot-PaperEdition]
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(SourceFile:734) ~[spigot.jar:git-iSpigot-PaperEdition]
	at java.lang.Thread.run(Thread.java:750) ~[?:1.8.0_362]
Caused by: java.lang.UnsupportedClassVersionError: gs/mclo/bukkit/MclogsPlugin has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_362]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:756) ~[?:1.8.0_362]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) ~[?:1.8.0_362]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:473) ~[?:1.8.0_362]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:74) ~[?:1.8.0_362]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:369) ~[?:1.8.0_362]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:363) ~[?:1.8.0_362]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_362]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:362) ~[?:1.8.0_362]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[spigot.jar:git-iSpigot-PaperEdition]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[?:1.8.0_362]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[?:1.8.0_362]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_362]
	at java.lang.Class.forName(Class.java:348) ~[?:1.8.0_362]
	at org.bukkit.plugin.java.PluginClassLoader.<init>(PluginClassLoader.java:65) ~[spigot.jar:git-iSpigot-PaperEdition]
	at org.bukkit.plugin.java.JavaPluginLoader.loadPlugin(JavaPluginLoader.java:130) ~[spigot.jar:git-iSpigot-PaperEdition]
	... 6 more`

**Comment by MiataBoy** [comment]
https://stackoverflow.com/questions/9170832/list-of-java-class-file-format-major-version-numbers

**Comment by JulianVennen** [comment]
> 1.8 Java isn't supported

That is correct

**Comment by Boryte** [comment]
> > 1.8 Java isn't supported
> 
> That is correct

That makes no sense. Why would you put on spigot that plugin support spigot 1.8 yet it doesn't support Java 8. You should add Java 8 support imo

**Comment by JulianVennen** [comment]
Where on SpigotMC does it say that it supports Java 8?

**Comment by Boryte** [comment]
> Where on SpigotMC does it say that it supports Java 8?

![Screenshot_20230707_164923_Chrome.jpg](https://github.com/aternosorg/mclogs/assets/91828774/ed5d6dab-01c0-4ab1-ad8f-8e21b2756235)

**Comment by JulianVennen** [comment]
I don't see any mention of Java Versions there.
It says *Tested Minecraft Version*

**Comment by RealmKebab** [comment]
> > I don't see any mention of Java Versions there.
> > It says _Tested Minecraft Version_
> > Clearly not tested since it doesn't work.
> > Spigot 1.8 can't be run on Java 8+ in production. Plus many plugins like worldedit do not support it.

![image](https://github.com/aternosorg/mclogs/assets/73048123/f5e5abd5-8adf-4f78-9704-d141404803d5)
